package conf

var OBJ_DETECT_MOD_SERVICE_PORT = "50052"
var OBJ_DETECT_MOD_POLICY = "SAVE" // {UPLOAD, SAVE}
var OBJ_DETECT_MOD_UPLOAD_THRESHOLD = float32(0.5)

var VISUAL_NAVIGATION_MOD_SERVICE_PORT = "50051"
var VISUAL_NAVIGATION_MOD_POLICY = "SAVE" // {UPLOAD, SAVE}

var CLOUDURL = "http://***REMOVED***:8000"
var AGENT_PORT = "8000"
var ROLE = "EDGE" // {CLOUD, EDGE}
